## Task 1

In [2]:
import numpy as np

In [3]:
%%time
# task 1 
def task_1():
    n = int(input("input n: "))
    
    a = np.arange(1, n + 1)
    a = np.diag(a)
    print(a)

task_1()

input n:  5


[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
CPU times: total: 0 ns
Wall time: 3.76 s


In [4]:
%%time
def task_1():
    n = int(input("input n: "))
    
    a = [[i + 1 if i == j else 0 for j in range(n)] for i in range(n)]
    
    for row in a:
        print(row)

task_1()

input n:  5


[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: total: 0 ns
Wall time: 4.09 s


In [5]:
%%time
# task 5
def task_5():
    n = int(input("input n: "))
    
    a = np.zeros((n, n), dtype=int)
    a[::2] = 1
    print(a)

task_5()

input n:  5


[[1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 1 1 1 1]]
CPU times: total: 0 ns
Wall time: 9.24 s


In [6]:
%%time
def task_5():
    n = int(input("input n: "))
    
    a = []
    
    for i in range(n):
        if i % 2 == 0:
            a.append([1] * n)
        else:
            a.append([0] * n)
    
    for row in a:
        print(row)

task_5()

input n:  5


[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
CPU times: total: 0 ns
Wall time: 1.65 s


In [7]:
%%time
# task 7
def task_7():
    a = np.array(list(map(int, input("input an array : ").split())))
    
    a[a == 0] = -1
    print(a)

task_7()

input an array :  1 2 0 3 0 4


[ 1  2 -1  3 -1  4]
CPU times: total: 0 ns
Wall time: 13.2 s


In [8]:
%%time
def task_7():
    a = list(map(int, input("Введіть масив: ").split()))
    
    for i in range(len(a)):
        if a[i] == 0:
            a[i] = -1
    
    print(a)

task_7()

Введіть масив:   1 2 0 3 0 4


[1, 2, -1, 3, -1, 4]
CPU times: total: 0 ns
Wall time: 13.7 s


In [9]:
%%time
# task 8
def task_8():
    a = np.array(list(map(int, input("input an array : ").split())))
    
    zeros = np.count_nonzero(a == 0)
    nonzeros = a.size - zeros

    print(f"zeros : {zeros}")
    print(f"non-zeros : {nonzeros}")

task_8()

input an array :  1 2 3 4 0 0 0 


zeros : 3
non-zeros : 4
CPU times: total: 0 ns
Wall time: 17.1 s


In [10]:
%%time

def task_8():
    a = list(map(int, input("input an array : ").split()))
    
    zeros = len([x for x in a if x == 0])
    nonzeros = len([x for x in a if x != 0])
    
    print(f"zeros : {zeros}")
    print(f"non-zeros : {nonzeros}")

task_8()

input an array :  1 2 3 4 0 0 0 


zeros : 3
non-zeros : 4
CPU times: total: 0 ns
Wall time: 7.45 s


In [11]:
%%time
# task 11
def task_11():
    n = int(input("input n: "))
    
    a = np.ones((n, n), dtype=int)
    frame = np.zeros((n + 2, n + 2), dtype=int)

    frame[1:-1, 1:-1] = a
    print(frame)

task_11()

input n:  10


[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
CPU times: total: 0 ns
Wall time: 8.46 s


In [12]:
%%time
def task_11():
    n = int(input("input n : "))
    
    a = [[0] * (n + 2) for _ in range(n + 2)]
    
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            a[i][j] = 1
    
    for row in a:
        print(row)

task_11()

input n :  10


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
CPU times: total: 0 ns
Wall time: 3.76 s


In [13]:
%%time
# task 14
def task_14():
    n = 8
    a = np.tile([0, 1], int(n * n / 2)).reshape(n, n)

    print(a)

task_14()

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]
CPU times: total: 0 ns
Wall time: 1.01 ms


In [14]:
%%time
def task_14():
    n = 8
    a = [[1 if (i + j) % 2 == 0 else 0 for j in range(n)] for i in range(n)]

    for row in a:
        print(row)

task_14()

[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
CPU times: total: 0 ns
Wall time: 0 ns


In [15]:
%%time
# task 16
def task_16():
    n = int(input("input n: "))
    
    a = np.arange(0, n + 1)
    a[(a > n / 4) & (a < 3 * n / 4)] = 0

    print(a)

task_16()

input n:  10


[ 0  1  2  0  0  0  0  0  8  9 10]
CPU times: total: 0 ns
Wall time: 3.65 s


In [16]:
%%time
def task_16():
    n = int(input("input n: "))
    
    a = [x if not (n / 4 < x < 3 * n / 4) else 0 for x in range(n + 1) ]
    
    print(a)

task_16()

input n:  10


[0, 1, 2, 0, 0, 0, 0, 0, 8, 9, 10]
CPU times: total: 0 ns
Wall time: 2.86 s


In [17]:
%%time
import numpy as np
# task 17
def task_17():
    n = int(input("input n: "))
    
    a = np.arange(0, n + 1)
    a[(a < n / 2) | (a > 3 * n / 4)] = -a[(a < n / 2) | (a > 3 * n / 4)]
#    a[(a < n / 2) & (a > 3 * n / 4)] = -a[(a < n / 2) & (a > 3 * n / 4)]
    print(a)

task_17()

input n:  10


[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
CPU times: total: 0 ns
Wall time: 11.4 s


In [18]:
%%time
def task_17():
    n = int(input("input n: "))
    
    a = [-x if (x < n / 2 or x > 3 * n / 4) else x for x in range(n + 1)]
    
    print(a)

task_17()

input n:  10


[0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10]
CPU times: total: 0 ns
Wall time: 6.71 s


In [19]:
%%time
# task 20
def task_20():
    n = int(input("input n: "))

    a = np.random.rand(n)
    print(f"initial vector : {a}")
    
    a[np.argmax(a)] = 0
    print(f"modified vector : {a}")

task_20()

input n:  7


initial vector : [0.31205952 0.7118077  0.48859971 0.95328671 0.95124138 0.63506114
 0.56774303]
modified vector : [0.31205952 0.7118077  0.48859971 0.         0.95124138 0.63506114
 0.56774303]
CPU times: total: 15.6 ms
Wall time: 13.4 s


In [20]:
%%time
def task_20():
    n = int(input("input n: "))

    a = np.random.rand(n)
    print(f"initial vector : {a}")

    max_value = max(a)
    print(f"max value : {max_value}")
    
    a = [0 if x == max_value else x for x in a]
    print(f"modified vector : {a}")

task_20()

input n:  7


initial vector : [0.92938772 0.7374764  0.04466395 0.82543476 0.01960033 0.05976144
 0.88408615]
max value : 0.9293877221276753
modified vector : [0, 0.737476403685355, 0.04466395222673092, 0.8254347579590202, 0.019600334068275327, 0.05976144272803252, 0.8840861540556861]
CPU times: total: 0 ns
Wall time: 3.72 s


## Task 2

Система рівнянь для розв'язання згідно варіанту 13:
\
\begin{cases}
5x_1+x_2-x_4=-9 \\
3x_1-3x_2+x_3+4x_4=-7 \\
3x_1-2x_2+x_4=-16 \\
x_1-4x_2+x_4=0
\end{cases}


In [23]:
import numpy as np

# Вихідні дані
A = np.array([[5, 1, 0, -1], [3, -3, 1, 4], [3, -2, 0, 1], [1, -4, 0, 1]])
b = np.array([-9, -7, -16, 0])

# 1. Формули Крамера
det_A = np.linalg.det(A)

# A не дорівнює нулю => система має 1 розв'язок
if det_A != 0:
    # Заміна стовпців
    x_length = A.shape[1]
    x_Cramer = np.zeros(x_length)
    
    for i in range(x_length):
        A_temp = A.copy()
        A_temp[:, i] = b
        det_A_temp = np.linalg.det(A_temp)
        x_Cramer[i] = det_A_temp / det_A
else:
    x_Cramer = None

# 2. Множення матриці
x_multiplication = np.linalg.inv(A).dot(b)

# 3. Обернена матриця
A_inv = np.linalg.inv(A)
x_inverse = A_inv.dot(b)

# 4. NumPy linalg.solve
x_numpy = np.linalg.solve(A, b)

# 5. Порівняння рішень
solutions_match = np.allclose(x_Cramer, x_multiplication) and np.allclose(x_Cramer, x_inverse) and np.allclose(x_Cramer, x_numpy)

x_Cramer, x_multiplication, x_inverse, x_numpy, solutions_match


(array([ -3.66666667,  -4.33333333,  45.66666667, -13.66666667]),
 array([ -3.66666667,  -4.33333333,  45.66666667, -13.66666667]),
 array([ -3.66666667,  -4.33333333,  45.66666667, -13.66666667]),
 array([ -3.66666667,  -4.33333333,  45.66666667, -13.66666667]),
 True)

# Task 3

Згідно варіанту 13 необхідно обчислити значення матричного виразу:

$$
(A + B)A - B(2A + 3B)
$$

Де
$$
A =    
\begin{bmatrix}
1 & -2 & 3 \\
2 & 3 & 3 \\
1 & 4 & -1
\end{bmatrix}
$$

$$
B = 
\begin{bmatrix}
4 & 11 & 3 \\
1 & 6 & 1 \\
2 & 2 & 16
\end{bmatrix}
$$

### Висновок
Обидва методи дали однакові результати, але можуть відрізнятися за часом виконання. Використання NumPy, як правило, 
є оптимальним вибором для роботи з матрицями завдяки векторизованим обчисленням.
екторизованим обчисленням.
 обчисленням.
екторизованим обчисленням.
торизованим обчисленням.
ризованим обчисленням.
енням.

In [26]:
import numpy as np
import time

# Визначення матриць A і B
A = np.array([[1,-2, 3],
              [2, 3, 5],
              [1, 4, -1]])

B = np.array([[4, 11, 3],
              [1, 6, 1],
              [2, 2, 16]])

####### NumPy
start_time_np = time.time()
result_numpy = (A + B) @ A - B @  (2 * A + 3* B)
end_time_np = time.time()
time_numpy = end_time_np - start_time_np

####### Обчислення виразу з використанням ітерацій
start_time_i = time.time()
def matrix_addition(X, Y):
    rows, cols = X.shape
    result = np.zeros((rows, cols), dtype=int)
    for i in range(rows):
        for j in range(cols):
            result[i][j] = X[i][j] + Y[i][j]
    return result

def matrix_multiplication(X, Y):
    rows_X, cols_X = X.shape
    rows_Y, cols_Y = Y.shape
    result = np.zeros((rows_X, cols_Y), dtype=int)
    for i in range(rows_X):
        for j in range(cols_Y):
            for k in range(cols_X):
                result[i][j] += X[i][k] * Y[k][j]
    return result

def scalar_multiplication(scalar, X):
    rows, cols = X.shape
    result = np.zeros((rows, cols), dtype=int)
    for i in range(rows):
        for j in range(cols):
            result[i][j] = scalar * X[i][j]
    return result

# (A + B)A
C = matrix_addition(A, B)
C_A = matrix_multiplication(C, A)

# B(2A + 3B)
two_A = scalar_multiplication(2, A)
three_B = scalar_multiplication(3, B)
D = matrix_addition(two_A, three_B)
D_B = matrix_multiplication(B, D)

# (A + B)A - B(2A + 3B)
result_iterative = matrix_addition(C_A, -D_B)
end_time_i = time.time()
time_iterative = end_time_i - start_time_i

# Порівняння результатів
comparison = np.allclose(result_numpy, result_iterative)

time_numpy, time_iterative, comparison, result_numpy, result_iterative


(0.0013751983642578125,
 0.0,
 True,
 array([[-128, -381, -287],
        [ -37, -142,  -91],
        [-140, -258, -768]]),
 array([[-128, -381, -287],
        [ -37, -142,  -91],
        [-140, -258, -768]]))